apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-app
spec:
  selector:
    matchLabels:
      app: order-service-app
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      containers:
      - name: order-service-app
        image: kreys326/order-service
        ports:
        - containerPort: 10097
        env:
        - name: CONFIG_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: common-cm
              key:  CONFIG_SERVER_URL
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: EUREKA_SERVER_ADDRESS
              name: common-cm
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: order-cm
        - name: ZIPKIN_SERVER_URL
          valueFrom:
            configMapKeyRef:
              key: ZIPKIN_SERVER_URL
              name: common-cm

---

apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
spec:
  selector:
    app: order-service-app
  ports:
  - port: 10097
    targetPort: 10097

