apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-app
spec:
  selector:
    matchLabels:
      app: product-service-app
  template:
    metadata:
      labels:
        app: product-service-app
    spec:
      containers:
      - name: product-service-app
        image: kreys326/product-service:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 10101
        env:
        - name: CONFIG_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: common-cm
              key:  CONFIG_SERVER_URL
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: EUREKA_SERVER_ADDRESS
              name: common-cm
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: product-cm
        - name: ZIPKIN_SERVER_URL
          valueFrom:
            configMapKeyRef:
              key: ZIPKIN_SERVER_URL
              name: common-cm

---

apiVersion: v1
kind: Service
metadata:
  name: product-service-svc
spec:
  selector:
    app: product-service-app
  ports:
  - port: 80
    targetPort: 10101

